version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
      - set -ex
      - printenv
      - ls -R
      - CURRENTDIR=`pwd`
      - curl -sS https://getcomposer.org/installer | php
      - php -c${CURRENTDIR}/php.ini composer.phar install --no-dev --no-progress

artifacts:
  files:
    - '**/*'
